def Clothing():
    clothing = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/t1411.jpg",
            "name": "Accessories",
            "sub1": "Bags",
            "sub2": "Jewellery",
            "sub3": "Luggage",
            "sub4": "Sunglasses",
            "sub5": "Umbrella",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/cl337.jpg",
            "name": "Shoes",
            "sub1": "Boots",
            "sub2": "Hells & Pumps",
            "sub3": "Low Shoes",
            "sub4": "Slippers & Sandals",
            "sub5": "Sport Shoes",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/cl10001.jpg",
            "name": "Clothing",
            "sub1": "Accessories",
            "sub2": "Dresses",
            "sub3": "Jumpsuits & Overalls",
            "sub4": "Outerwear",
            "sub5": "Skirts",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/cl1194.jpg",
            "name": "Children's Shoes",
            "sub1": "Ballerinas",
            "sub2": "Beach Shoes",
            "sub3": "Boots",
            "sub4": "Espadrilles",
            "sub5": "First Steps",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/cl734.jpg",
            "name": "Work Clothes",
            "sub1": "Protective Wears",
            "sub2": "Work Gloves",
            "sub3": "Work Shoes",
            "sub4": "Work Wears",
            "sub5": "",
        },
        {
            "id": 6,
            "img": "https://pricerunner.com/category/138x138/cl359.jpg",
            "name": "Children's Clothing",
            "sub1": "Accessories",
            "sub2": "Base Layer",
            "sub3": "Bodysuits",
            "sub4": "Christening Garments",
            "sub5": "Dresses",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl730.jpg",
            "name": "Fancy Dresses",
            "sub1": "Accessories",
            "sub2": "Colored Lenses",
            "sub3": "Fancy Dresses",
            "sub4": "Headgear",
            "sub5": "Makeup",
        },
        {
            "id": 8,
            "img": "https://www.pricerunner.com/category/138x138/cl696.jpg",
            "name": "Shoe Care & Accessories",
            "sub1": "Ice Grips & Crampons",
            "sub2": "Insoles",
            "sub3": "Shoe Accessories",
            "sub4": "Shoe Care",
            "sub5": "",
        },
    ];

    return clothing
