def Computing():
    computing = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/t22.jpg",
            "name": "Computers",
            "sub1": "Desktop Computers",
            "sub2": "Laptops",
            "sub3": "Single-Board Computers",
            "sub4": "Tablets",
            "sub5": "eReaders",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/t23.jpg",
            "name": "Peripherals",
            "sub1": "3D Printing",
            "sub2": "Computer Accessories",
            "sub3": "Computer Mic",
            "sub4": "Graphic Tablets",
            "sub5": "Ink & Toners",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/t9.jpg",
            "name": "Components",
            "sub1": "CPUs",
            "sub2": "Capture & TV Cards",
            "sub3": "Computer Cases",
            "sub4": "Computer Cooling",
            "sub5": "Computer Cards",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/t24.jpg",
            "name": "Storage",
            "sub1": "External Enclosures",
            "sub2": "Hard Drives",
            "sub3": "Memory Card Readers",
            "sub4": "Memory Card & USB Flash Drives",
            "sub5": "NAS Servers",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/t47.jpg",
            "name": "Software",
            "sub1": "Office Software",
            "sub2": "Operating Software",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 6,
            "img": "https://www.pricerunner.com/category/138x138/t20.jpg",
            "name": "Networking",
            "sub1": "Access Points,Bridges & Repeaters",
            "sub2": "Firewalls",
            "sub3": "KVM Switches",
            "sub4": "Media Converters",
            "sub5": "Mobile Modems",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl10014.jpg",
            "name": "Computer Spare Parts",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
    ];

    return computing
