def Yourself():
    yourself = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/t1492.jpg",
            "name": "Tools & Machines",
            "sub1": "Drills & Screwdrivers",
            "sub2": "Grinders & Polishers",
            "sub3": "Hand Tools",
            "sub4": "Power Saws",
            "sub5": "Power Tools",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/t1432.jpg",
            "name": "Building Materials",
            "sub1": "Building Materials",
            "sub2": "Doors",
            "sub3": "Electrical Accessories",
            "sub4": "Garage Doors",
            "sub5": "Insulation",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/t1491.jpg",
            "name": "Conservatories, Outbuildings & Sheds",
            "sub1": "Conservatories",
            "sub2": "Outbuildings",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/t1490.jpg",
            "name": "Floor, Wall & Roof",
            "sub1": "Flooring",
            "sub2": "Moulding & Millwork",
            "sub3": "Paint",
            "sub4": "Roof Equipment",
            "sub5": "Solar Panels",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/t1434.jpg",
            "name": "Heating & Plumbing",
            "sub1": "Boilers",
            "sub2": "Fireplaces",
            "sub3": "Heating Pumps",
            "sub4": "Pellets & Briquettes",
            "sub5": "Plumbing",
        },
        {
            "id": 6,
            "img": "https://www.pricerunner.com/category/138x138/cl346.jpg",
            "name": "DIY Accessories",
            "sub1": "Casters",
            "sub2": "Furniture Dollys",
            "sub3": "Ladders",
            "sub4": "Pallet Trucks",
            "sub5": "Sack Barrows",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl1406.jpg",
            "name": "Kitchen Sinks",
            "sub1": "Corner Sinks",
            "sub2": "Drainboard Sinks",
            "sub3": "Full-Size Sinks",
            "sub4": "Kitchen Sinks",
            "sub5": "Worktops",
        },
        {
            "id": 8,
            "img": "https://www.pricerunner.com/category/138x138/cl1298.jpg",
            "name": "Bricks & Paving",
            "sub1": "Blocks & Bricks",
            "sub2": "Bricks & Paving Accessories",
            "sub3": "Groundwork",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 9,
            "img": "https://www.pricerunner.com/category/138x138/cl724.jpg",
            "name": "Kitchen Units",
            "sub1": "Kitchen Cabinets",
            "sub2": "Kitchen Islands",
            "sub3": "Mini Kitchena",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 10,
            "img": "https://www.pricerunner.com/category/138x138/cl10015.jpg",
            "name": "Waste Disposal Unit",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
    ];

    return yourself
