def Entertainment():
    Gaming = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/cl52.jpg",
            "name": "Game Consoles",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/cl165.jpg",
            "name": "Game Controllers",
            "sub1": "Arcade Sticks",
            "sub2": "Flight Controls",
            "sub3": "Gamepads",
            "sub4": "Music Instruments",
            "sub5": "Wheels & Racing Controls",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/t1477.jpg",
            "name": "Games",
            "sub1": "Mac Games",
            "sub2": "Nintendo 3DS Games",
            "sub3": "Nintendo Switch Games",
            "sub4": "Nintendo Wii U Games",
            "sub5": "PC Games",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/cl1469.jpg",
            "name": "VR-Virtual Reality",
            "sub1": "Mobile VR headsets",
            "sub2": "VR Accessories",
            "sub3": "VR Headsets",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/t40.jpg",
            "name": "Books,Movies & Music",
            "sub1": "Books",
            "sub2": "CD & Vinyl Storage",
            "sub3": "Movies",
            "sub4": "Music",
            "sub5": "",
        },
        {
            "id": 6,
            "img": "https://www.pricerunner.com/category/138x138/cl1615.jpg",
            "name": "Gaming Chairs",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl196.jpg",
            "name": "Gaming Accessories",
            "sub1": "Batteries & Charging Stations",
            "sub2": "Controllers & Console Stands",
            "sub3": "Controller Add-ons",
            "sub4": "Gaming Desks",
            "sub5": "Merchandies & Collectibles",
        },
        {
            "id": 8,
            "img": "https://www.pricerunner.com/category/138x138/cl196.jpg",
            "name": "Retro Games",
            "sub1": "Dreamcast Games",
            "sub2": "GameBoy Advance Games",
            "sub3": "GameCube Games",
            "sub4": "Nintendo DS Games",
            "sub5": "Nintendo Wii Games",
        },
    ];

    return Gaming
