def Interior():
    HomeInteriorData = [
        {
            "id": 1,
            "name": "Home Appliances",
            "img": "https://www.pricerunner.com/category/138x138/t3.jpg",
            "sub1": "Cookers and Ovens",
            "sub2": "Dishwashers",
            "sub3": "Extractor Fans",
            "sub4": "Fridges & Freezers",
            "sub5": "Microwave Ovens",
        },
        {
            "id": 2,
            "name": "Kitchen Appliances",
            "img": "https://www.pricerunner.com/category/138x138/t14.jpg",
            "sub1": "Blenders",
            "sub2": "Blowtorches",
            "sub3": "Breadmakers",
            "sub4": "Coffee Grinders",
            "sub5": "Coffee Makers",
        },
        {
            "id": 3,
            "name": "Interior and Furniture",
            "img": "https://www.pricerunner.com/category/138x138/t1428.jpg",
            "sub1": "Bads & Mattresses",
            "sub2": "Carpet & Rugs",
            "sub3": "Curtains & Accessories",
            "sub4": "Flowers",
            "sub5": "Furniture",
        },
        {
            "id": 4,
            "name": "Home",
            "img": "https://www.pricerunner.com/category/138x138/t1426.jpg",
            "sub1": "Air Treatment",
            "sub2": "Alarm Clocks",
            "sub3": "Ashtrays",
            "sub4": "Batteries & Chargers",
            "sub5": "Cleaning Equipment and Cleaning Agents",
        },
        {
            "id": 5,
            "name": "Bathroom and Sauna",
            "img": "https://www.pricerunner.com/category/138x138/t1446.jpg",
            "sub1": "Bathroom Accessories",
            "sub2": "Bathroom Furniture",
            "sub3": "Bathroom Sinks",
            "sub4": "Heated Towel Rails",
            "sub5": "Saunas",
        },
        {
            "id": 6,
            "name": "Kitchen",
            "img": "https://www.pricerunner.com/category/138x138/t1448.jpg",
            "sub1": "Bakeware",
            "sub2": "Cookware",
            "sub3": "Kitchen Accessories",
            "sub4": "Kitchen Knives",
            "sub5": "Spice Racks",
        },
        {
            "id": 7,
            "name": "Food & Wine",
            "img": "https://www.pricerunner.com/category/138x138/t251.jpg",
            "sub1": "Beer & Spirits",
            "sub2": "Food & Drinks",
            "sub3": "Wines",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 8,
            "name": "Gift Card",
            "img": "https://www.pricerunner.com/category/138x138/cl10007.jpg",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 9,
            "name": "Office Equipment",
            "img": "https://www.pricerunner.com/category/138x138/t36.jpg",
            "sub1": "Barcode Scannners",
            "sub2": "Binding Machine",
            "sub3": "Calculator",
            "sub4": "Laminating Machine",
            "sub5": "Office Supplies",
        },
        {
            "id": 10,
            "name": "Advent Calendars",
            "img": "https://www.pricerunner.com/category/138x138/cl10028.jpg",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
    ];

    return HomeInteriorData
