def Phone():
    phoneWearables = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/cl1.jpg",
            "name": "Mobile Phones",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/cl1438.jpg",
            "name": "Wearables",
            "sub1": "Activity Clips",
            "sub2": "Activity Trackers",
            "sub3": "Chest Strap Heart Rate Monitors",
            "sub4": "Smartwatch Straps",
            "sub5": "Smartwatches",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/cl10068.jpg",
            "name": "GPS & Bluetooth Tracker",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/cl10.jpg",
            "name": "Landline Phones",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/cl288.jpg",
            "name": "Sat navs",
            "sub1": "Car Navigation",
            "sub2": "GPS Accessories",
            "sub3": "GPS Modules",
            "sub4": "Handheld GPS Modules",
            "sub5": "",
        },
        {
            "id": 6,
            "img": "https://www.pricerunner.com/category/138x138/cl199.jpg",
            "name": "Mobile Phone Accessories",
            "sub1": "Cases & Covers",
            "sub2": "Mobile Phone Cleaning",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl10037.jpg",
            "name": "Phone Device Holder",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 8,
            "img": "https://www.pricerunner.com/category/138x138/cl10061.jpg",
            "name": "Screen Protectors",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 9,
            "img": "https://www.pricerunner.com/category/138x138/cl10057.jpg",
            "name": "Replacement Chassis",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 10,
            "img": "https://www.pricerunner.com/category/138x138/cl10054.jpg",
            "name": "Replacement Screens",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 11,
            "img": "https://www.pricerunner.com/category/138x138/cl10058.jpg",
            "name": "Camera Module Replacements",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 12,
            "img": "https://www.pricerunner.com/category/138x138/cl10055.jpg",
            "name": "Charging Ports",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 13,
            "img": "https://www.pricerunner.com/category/138x138/cl10064.jpg",
            "name": "Fingerprint Sensors",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 14,
            "img": "https://www.pricerunner.com/category/138x138/cl10065.jpg",
            "name": "Replacement Antennas",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 15,
            "img": "https://www.pricerunner.com/category/138x138/cl10059.jpg",
            "name": "Replacement Buttons",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 16,
            "img": "https://www.pricerunner.com/category/138x138/cl10060.jpg",
            "name": "Replacement Speakers",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 17,
            "img": "https://www.pricerunner.com/category/138x138/cl10056.jpg",
            "name": "SIM Card Trays",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 18,
            "img": "https://www.pricerunner.com/category/138x138/cl10062.jpg",
            "name": "Screen Adhesive Tapes",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 19,
            "img": "https://www.pricerunner.com/category/138x138/cl10063.jpg",
            "name": "Vibration Motors",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
    ];

    return phoneWearables
