def Photography():
    photography = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/cl8.jpg",
            "name": "Camcorders",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/cl29.jpg",
            "name": "Digital Cameras",
            "sub1": "Bridge Cameras",
            "sub2": "Compact Cameras",
            "sub3": "DSLR Cameras",
            "sub4": "Mirrorless Cameras",
            "sub5": "",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/cl126.jpg",
            "name": "Analogue Cameras",
            "sub1": "Camera Film",
            "sub2": "Instant Cameras",
            "sub3": "Instant Film",
            "sub4": "Single-Use Cameras",
            "sub5": "",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/cl281.jpg",
            "name": "Camera Tripods",
            "sub1": "Tripod & Monopod Accessories",
            "sub2": "Tripod Heads",
            "sub3": "Tripods",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/cl543.jpg",
            "name": "Camera Lenses",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 6,
            "img": "https://www.pricerunner.com/category/138x138/cl280.jpg",
            "name": "Camera Bags",
            "sub1": "Accessories Bags & Organizers",
            "sub2": "Camera Bags & Cases",
            "sub3": "Transport Cases & Carrying Bags",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl200.jpg",
            "name": "Camera Accessories",
            "sub1": "Action Camera Accessories",
            "sub2": "Analogue Camera Accessories",
            "sub3": "Camera & Sensor Cleaning",
            "sub4": "Camera Grips",
            "sub5": "Camera Monitors",
        },
        {
            "id": 8,
            "img": "https://www.pricerunner.com/category/138x138/cl587.jpg",
            "name": "Lighting & Studio Equipment",
            "sub1": "Light & Background Stands",
            "sub2": "Studio Lighting",
            "sub3": "Tables & Light Tents",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 9,
            "img": "https://www.pricerunner.com/category/138x138/cl282.jpg",
            "name": "Camera Lens Filter",
            "sub1": "Filter Accessories",
            "sub2": "Lens Filters",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 10,
            "img": "https://www.pricerunner.com/category/138x138/cl283.jpg",
            "name": "Camera Flashes",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 11,
            "img": "https://www.pricerunner.com/category/138x138/cl622.jpg",
            "name": "Digital Photo Frame",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 12,
            "img": "https://www.pricerunner.com/category/138x138/cl1569.jpg",
            "name": "Colour Calibrators",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 13,
            "img": "https://www.pricerunner.com/category/138x138/cl10034.jpg",
            "name": "Shutter Releases",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 14,
            "img": "https://www.pricerunner.com/category/138x138/cl10066.jpg",
            "name": "Photo Backgrounds",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
    ];
    return photography;
