def Hobbie():
    Toys = [
        {
            "id": 1,
            "img": "https://www.pricerunner.com/category/138x138/cl1559.jpg",
            "name": "RC Toys",
            "sub1": "Drones",
            "sub2": "RC Accessories",
            "sub3": "RC Airplanes",
            "sub4": "RC Boats",
            "sub5": "RC Cars",
        },
        {
            "id": 2,
            "img": "https://www.pricerunner.com/category/138x138/cl72.jpg",
            "name": "Toys",
            "sub1": "Baby Toys",
            "sub2": "Ball Pit",
            "sub3": "Bath Toys",
            "sub4": "Building Games",
            "sub5": "Classic Toys",
        },
        {
            "id": 3,
            "img": "https://www.pricerunner.com/category/138x138/cl613.jpg",
            "name": "Board Games",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 4,
            "img": "https://www.pricerunner.com/category/138x138/cl1290.jpg",
            "name": "Trampolines",
            "sub1": "Trampolines Accessories",
            "sub2": "Trampolines",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 5,
            "img": "https://www.pricerunner.com/category/138x138/cl1342.jpg",
            "name": "Arts & Craft",
            "sub1": "Casting",
            "sub2": "Crafts",
            "sub3": "Glue",
            "sub4": "Paint",
            "sub5": "Clay",
        },
        {
            "id": 6,
            "img": "https://www.pricerunner.com/category/138x138/cl627.jpg",
            "name": "Scale Models & Model Kits",
            "sub1": "Car Track",
            "sub2": "Model Kit",
            "sub3": "Model Railway",
            "sub4": "Slot Cars",
            "sub5": "",
        },
        {
            "id": 7,
            "img": "https://www.pricerunner.com/category/138x138/cl1368.jpg",
            "name": "Table Sports",
            "sub1": "",
            "sub2": "",
            "sub3": "",
            "sub4": "",
            "sub5": "",
        },
        {
            "id": 8,
            "img": "https://www.pricerunner.com/category/138x138/cl339.jpg",
            "name": "Jigsaw Puzzles",
            "sub1": "3D-Jigsaw Puzzles",
            "sub2": "4D-Jigsaw Puzzles",
            "sub3": "Classic Jigsaw Puzzles",
            "sub4": "Draw-yourself Puzzles",
            "sub5": "Floor Jigsaw Puzzles",
        },
    ];

    return Toys
